### ISSUE TITLE
print_exponential_number()'s variable "abs_exp10_covered_by_powers_table" may be really uninitialized

### ISSUE THREAD

**Issue by me9atherion** [eyalroz/printf#158] opened 2023-08-09 22:14 UTC
https://github.com/eyalroz/printf/blob/5190e484100b19b076fb852893c6bcfd5624c1a4/src/printf/printf.c#L939C1-L939C1

Most recent GCC 12 compiler from ARM complained for potential uninitialization of "abs_exp10_covered_by_powers_table" variable also (I built code from "master" branch, not "develop"). And I noticed that probably this is really a bug. "abs_exp10_covered_by_powers_table" is a boolean variable which is declared without an initialization. And it receives the initial value conditionally only in else branch of checking the condition "if(abs_number == 0.0)". So, I suspect that it is really a bug and adding this pragma here really hides the problem, not solves it.

**Comment by eyalroz** [comment] 2023-08-09 22:25
Duplicate of #123 .

**Closed by eyalroz** 2023-08-09 22:25 UTC
